name: laravel-eindwerk
recipe: laravel
config:
  php: "8.3" # match your PHP version
  via: nginx # use Nginx instead of Apache :contentReference[oaicite:0]{index=0}
  webroot: app/public # point at your Laravel “public” folder :contentReference[oaicite:1]{index=1}
  xdebug: false
  composer_version: "2"
  database: mariadb:10.11
services:
  node:
    type: node:22 # or whatever Node version you like

tooling:
  npm:
    service: node
  yarn:
    service: node
